name: scispacy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - catalogue=2.0.10
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - cymem=2.0.10
  - cython-blis=1.0.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - jinja2=3.1.4
  - joblib=1.4.2
  - language-data=1.3.0
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.5
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pip=24.3.1
  - preshed=3.0.9
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - scikit-learn=1.6.0
  - scipy=1.13.1
  - shellingham=1.5.4
  - six=1.17.0
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - blis==0.7.11
      - certifi==2024.12.14
      - cloudpathlib==0.16.0
      - confection==0.1.5
      - conllu==6.0.0
      - emoji==2.14.0
      - filelock==3.16.1
      - fsspec==2024.10.0
      - langcodes==3.5.0
      - marisa-trie==1.2.1
      - mpmath==1.3.0
      - murmurhash==1.0.11
      - networkx==3.2.1
      - nltk==3.9.1
      - nmslib==2.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - owlready2==0.47
      - protobuf==5.29.1
      - psutil==6.1.0
      - pybind11==2.6.1
      - pysbd==0.3.4
      - regex==2024.11.6
      - scispacy==0.5.5
      - setuptools==75.6.0
      - smart-open==6.4.0
      - spacy==3.7.4
      - srsly==2.5.0
      - stanza==1.9.2
      - sympy==1.13.1
      - thinc==8.2.5
      - tomli==2.2.1
      - torch==2.5.1
      - triton==3.1.0
      - typer==0.9.4
      - wasabi==1.1.3
      - weasel==0.3.4
